drop table wte_test_data if exists;

create table wte_test_data (
	id bigint generated by default as identity (start with 1), 
	int_value bigint,	
	dec_value decimal(12,4),
	timestamp_value timestamp, 
	date_value date,
	time_value time, 
	string_value varchar(100),	
	primary key (id));

insert into wte_test_data	(int_value,	dec_value, timestamp_value, date_value,	time_value, string_value)
	values	(4567, 123.5678, '2014-01-16 12:05:22', '2014-01-17', '13:20:15.034900', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt');
