INSERT INTO WTE_TEMPLATE_PROPERTIES (TEMPLATE_ID, PROPERTY_KEY, PROPERTY_VALUE) VALUES (1, 'key1', 'value1');
INSERT INTO WTE_TEMPLATE_PROPERTIES (TEMPLATE_ID, PROPERTY_KEY, PROPERTY_VALUE) VALUES (1, 'key2', 'value2*');
INSERT INTO WTE_TEMPLATE_PROPERTIES (TEMPLATE_ID, PROPERTY_KEY, PROPERTY_VALUE) VALUES (2, 'key1', 'value1');
INSERT INTO WTE_TEMPLATE_PROPERTIES (TEMPLATE_ID, PROPERTY_KEY, PROPERTY_VALUE) VALUES (2, 'key2', 'value2');
INSERT INTO WTE_TEMPLATE_PROPERTIES (TEMPLATE_ID, PROPERTY_KEY, PROPERTY_VALUE) VALUES (2, 'key3', 'value3');
INSERT INTO WTE_TEMPLATE_PROPERTIES (TEMPLATE_ID, PROPERTY_KEY, PROPERTY_VALUE) VALUES (4, 'key3', 'value3');
INSERT INTO WTE_TEMPLATE_PROPERTIES (TEMPLATE_ID, PROPERTY_KEY, PROPERTY_VALUE) VALUES (4, 'key4', 'value4');
